function [ dbg ] = aga_aux_empty_dbg ( decoded )
%aga_aux_empty_dbg Empty AGA debug data
%   Builds the debug output structure returned by aga_fun_cost.
%
% Inputs:
%   decoded: decoded chromosome data structure
%
% Outputs:
%   dbg: debug data structure
%
% Example:
%   [ dbg ] = aga_aux_empty_dbg ( decoded );
%
% References:
%   [-]
%
%May 2026

dbg = struct( ...
    'isFeasible', false, ...
    'failureReason', "Not evaluated.", ...
    'decoded', decoded, ...
    'totalDv', Inf, ...
    'dV_GA1', NaN, ...
    'dV_DSM', NaN, ...
    'dV_GA2', NaN, ...
    'revs_before', NaN, ...
    'rp1', NaN, ...
    'rp2', NaN, ...
    'r_m', [NaN NaN NaN], ...
    'v_m_minus', [NaN NaN NaN], ...
    'v_m_plus', [NaN NaN NaN], ...
    'vinf_in', [NaN NaN NaN], ...
    'va', [NaN NaN NaN]);

end
